packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.11.0
    '@antfu/ni': ^24.3.0
    '@antfu/utils': ^9.1.0
    '@types/node': ^22.13.13
    '@unocss/preset-mini': ^66.0.0
    '@unocss/reset': ^66.0.0
    '@vitejs/plugin-vue': ^5.2.3
    bumpp: ^10.1.0
    eslint: ^9.23.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    unocss: ^66.0.0
    vite: ^6.2.3
    vite-plugin-inspect: ^11.0.0
    vitest: ^3.0.9
    vue: ^3.5.13
    vue-tsc: ^2.2.8
  frontend:
    nanoevents: ^9.1.0
  prod:
    estree-walker: ^3.0.3
    exsolve: ^1.0.4
    magic-string: ^0.30.17
    pathe: ^2.0.3
    source-map-js: ^1.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
