catalogMode: prefer

ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.1
    '@antfu/ni': ^28.0.0
    '@antfu/utils': ^9.3.0
    '@types/node': ^25.0.2
    '@unocss/preset-mini': ^66.5.10
    '@unocss/reset': ^66.5.10
    '@vitejs/devtools': ^0.0.0-alpha.20
    '@vitejs/devtools-kit': ^0.0.0-alpha.20
    '@vitejs/plugin-vue': ^6.0.3
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.5.10
    vite: ^7.3.0
    vite-plugin-inspect: ^11.3.3
    vitest: ^4.0.15
    vue: ^3.5.25
    vue-tsc: ^3.1.8
  frontend:
    nanoevents: ^9.1.0
  prod:
    estree-walker: ^3.0.3
    exsolve: ^1.0.8
    magic-string: ^0.30.21
    pathe: ^2.0.3
    source-map-js: ^1.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
