packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    '@antfu/utils': ^9.2.1
    '@types/node': ^24.5.2
    '@unocss/preset-mini': ^66.5.2
    '@unocss/reset': ^66.5.2
    '@vitejs/plugin-vue': ^6.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.5
    typescript: ^5.9.2
    unbuild: ^3.6.1
    unocss: ^66.5.2
    vite: ^7.1.7
    vite-plugin-inspect: ^11.3.3
    vitest: ^3.2.4
    vue: ^3.5.21
    vue-tsc: ^3.0.8
  frontend:
    nanoevents: ^9.1.0
  prod:
    estree-walker: ^3.0.3
    exsolve: ^1.0.7
    magic-string: ^0.30.19
    pathe: ^2.0.3
    source-map-js: ^1.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
