packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    '@antfu/utils': ^9.3.0
    '@types/node': ^24.10.0
    '@unocss/preset-mini': ^66.5.5
    '@unocss/reset': ^66.5.5
    '@vitejs/devtools': ^0.0.0-alpha.16
    '@vitejs/devtools-kit': ^0.0.0-alpha.16
    '@vitejs/plugin-vue': ^6.0.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.6
    typescript: ^5.9.3
    unbuild: ^3.6.1
    unocss: ^66.5.5
    vite: ^7.2.2
    vite-plugin-inspect: ^11.3.3
    vitest: ^4.0.8
    vue: ^3.5.24
    vue-tsc: ^3.1.3
  frontend:
    nanoevents: ^9.1.0
  prod:
    estree-walker: ^3.0.3
    exsolve: ^1.0.7
    magic-string: ^0.30.21
    pathe: ^2.0.3
    source-map-js: ^1.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
