packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@types/node': ^24.0.7
    '@unocss/preset-mini': ^66.3.2
    '@unocss/reset': ^66.3.2
    '@vitejs/plugin-vue': ^6.0.0
    bumpp: ^10.2.0
    eslint: ^9.30.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    unocss: ^66.3.2
    vite: ^7.0.0
    vite-plugin-inspect: ^11.3.0
    vitest: ^3.2.4
    vue: ^3.5.17
    vue-tsc: ^2.2.10
  frontend:
    nanoevents: ^9.1.0
  prod:
    estree-walker: ^3.0.3
    exsolve: ^1.0.7
    magic-string: ^0.30.17
    pathe: ^2.0.3
    source-map-js: ^1.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
